### ISSUE TITLE
Need a newer pulsar-spark version with pulsar-cient version 2.9+

### ISSUE THREAD

**Issue by grssam** [streamnative/pulsar-spark#88]
We are trying to use this adapter with pyspark. One of the challenges we are facing is setting custom subscription name for the individual readers that are created. The current version - 3.1.1.4 uses pulsar client 2.4 which doesn't have a way to set the full subscription name to something custom. It always appends a random UUID string.

Latest pulsar client 2.9 fixes that. This repo's master branch is already updated to 2.9 pulsar client but there has been no release out of master since.
When we tried locally building from master which has the pulsar client 2.9 dependency, (or taking the 3.1 branch and updating pulsar-client version to 2.9), we get the following error from pyspark when we eventually use the jar:

```
java.lang.ExceptionInInitializerError
        at org.apache.spark.sql.pulsar.PulsarProvider$.$anonfun$getClientParams$3(PulsarProvider.scala:259)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.immutable.Map$Map2.foreach(Map.scala:273)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.sql.pulsar.PulsarProvider$.getClientParams(PulsarProvider.scala:258)
        at org.apache.spark.sql.pulsar.PulsarProvider$.org$apache$spark$sql$pulsar$PulsarProvider$$prepareConfForReader(PulsarProvider.scala:513)
        at org.apache.spark.sql.pulsar.PulsarProvider.sourceSchema(PulsarProvider.scala:60)
        at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:236)
        at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:118)
        at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:118)
        at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:34)
        at org.apache.spark.sql.streaming.DataStreamReader.loadInternal(DataStreamReader.scala:168)
        at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
Caused by: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class InterfaceAudience
```

**Comment by jsteggink** [comment]
+1
We are facing the exact same issue.

**Comment by syhily** [comment]
Resolved in #89

**Comment by jsteggink** [comment]
After building with this fix, this error still occurs: "Caused by: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class InterfaceAudience"

**Comment by grssam** [comment]
@syhily Not sure why you have closed this ticket as there is still no new release beyond 3.1.1.4 back in June.

I have created another ticket #91 since I do not have permission to reopen this one.
